/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LabRouteImport } from './routes/lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as WalletWalletsRouteImport } from './routes/wallet/wallets'
import { Route as WalletSendRouteImport } from './routes/wallet/send'
import { Route as WalletReceiveRouteImport } from './routes/wallet/receive'
import { Route as WalletManagementRouteImport } from './routes/wallet/management'
import { Route as SetupImportRouteImport } from './routes/setup/import'
import { Route as SetupCreateRouteImport } from './routes/setup/create'
import { Route as LibraryTagsRouteImport } from './routes/library/tags'
import { Route as LibraryHistoryRouteImport } from './routes/library/history'
import { Route as LibraryFavoritesRouteImport } from './routes/library/favorites'
import { Route as LabTransactionsRouteImport } from './routes/lab/transactions'
import { Route as LabLayer2RouteImport } from './routes/lab/layer-2'
import { Route as LabControlRouteImport } from './routes/lab/control'
import { Route as LabBlocksRouteImport } from './routes/lab/blocks'
import { Route as LibraryArticlesSlugRouteImport } from './routes/library/articles.$slug'
import { Route as LabTxTxidRouteImport } from './routes/lab/tx.$txid'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const WalletWalletsRoute = WalletWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSendRoute = WalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletReceiveRoute = WalletReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletManagementRoute = WalletManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => WalletRoute,
} as any)
const SetupImportRoute = SetupImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCreateRoute = SetupCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SetupRoute,
} as any)
const LibraryTagsRoute = LibraryTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryHistoryRoute = LibraryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryFavoritesRoute = LibraryFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => LibraryRoute,
} as any)
const LabTransactionsRoute = LabTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LabRoute,
} as any)
const LabLayer2Route = LabLayer2RouteImport.update({
  id: '/layer-2',
  path: '/layer-2',
  getParentRoute: () => LabRoute,
} as any)
const LabControlRoute = LabControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => LabRoute,
} as any)
const LabBlocksRoute = LabBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LabRoute,
} as any)
const LibraryArticlesSlugRoute = LibraryArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => LibraryRoute,
} as any)
const LabTxTxidRoute = LabTxTxidRouteImport.update({
  id: '/tx/$txid',
  path: '/tx/$txid',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/lab/blocks': typeof LabBlocksRoute
  '/lab/control': typeof LabControlRoute
  '/lab/layer-2': typeof LabLayer2Route
  '/lab/transactions': typeof LabTransactionsRoute
  '/library/favorites': typeof LibraryFavoritesRoute
  '/library/history': typeof LibraryHistoryRoute
  '/library/tags': typeof LibraryTagsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/wallet/management': typeof WalletManagementRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/wallets': typeof WalletWalletsRoute
  '/lab/': typeof LabIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/lab/tx/$txid': typeof LabTxTxidRoute
  '/library/articles/$slug': typeof LibraryArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/lab/blocks': typeof LabBlocksRoute
  '/lab/control': typeof LabControlRoute
  '/lab/layer-2': typeof LabLayer2Route
  '/lab/transactions': typeof LabTransactionsRoute
  '/library/favorites': typeof LibraryFavoritesRoute
  '/library/history': typeof LibraryHistoryRoute
  '/library/tags': typeof LibraryTagsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/wallet/management': typeof WalletManagementRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/wallets': typeof WalletWalletsRoute
  '/lab': typeof LabIndexRoute
  '/library': typeof LibraryIndexRoute
  '/setup': typeof SetupIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/lab/tx/$txid': typeof LabTxTxidRoute
  '/library/articles/$slug': typeof LibraryArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/lab/blocks': typeof LabBlocksRoute
  '/lab/control': typeof LabControlRoute
  '/lab/layer-2': typeof LabLayer2Route
  '/lab/transactions': typeof LabTransactionsRoute
  '/library/favorites': typeof LibraryFavoritesRoute
  '/library/history': typeof LibraryHistoryRoute
  '/library/tags': typeof LibraryTagsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/wallet/management': typeof WalletManagementRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/wallets': typeof WalletWalletsRoute
  '/lab/': typeof LabIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/lab/tx/$txid': typeof LabTxTxidRoute
  '/library/articles/$slug': typeof LibraryArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/library'
    | '/settings'
    | '/setup'
    | '/wallet'
    | '/lab/blocks'
    | '/lab/control'
    | '/lab/layer-2'
    | '/lab/transactions'
    | '/library/favorites'
    | '/library/history'
    | '/library/tags'
    | '/setup/create'
    | '/setup/import'
    | '/wallet/management'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/wallets'
    | '/lab/'
    | '/library/'
    | '/setup/'
    | '/wallet/'
    | '/lab/tx/$txid'
    | '/library/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/lab/blocks'
    | '/lab/control'
    | '/lab/layer-2'
    | '/lab/transactions'
    | '/library/favorites'
    | '/library/history'
    | '/library/tags'
    | '/setup/create'
    | '/setup/import'
    | '/wallet/management'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/wallets'
    | '/lab'
    | '/library'
    | '/setup'
    | '/wallet'
    | '/lab/tx/$txid'
    | '/library/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/library'
    | '/settings'
    | '/setup'
    | '/wallet'
    | '/lab/blocks'
    | '/lab/control'
    | '/lab/layer-2'
    | '/lab/transactions'
    | '/library/favorites'
    | '/library/history'
    | '/library/tags'
    | '/setup/create'
    | '/setup/import'
    | '/wallet/management'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/wallets'
    | '/lab/'
    | '/library/'
    | '/setup/'
    | '/wallet/'
    | '/lab/tx/$txid'
    | '/library/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  WalletRoute: typeof WalletRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/wallet/wallets': {
      id: '/wallet/wallets'
      path: '/wallets'
      fullPath: '/wallet/wallets'
      preLoaderRoute: typeof WalletWalletsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/send': {
      id: '/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof WalletSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/receive': {
      id: '/wallet/receive'
      path: '/receive'
      fullPath: '/wallet/receive'
      preLoaderRoute: typeof WalletReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/management': {
      id: '/wallet/management'
      path: '/management'
      fullPath: '/wallet/management'
      preLoaderRoute: typeof WalletManagementRouteImport
      parentRoute: typeof WalletRoute
    }
    '/setup/import': {
      id: '/setup/import'
      path: '/import'
      fullPath: '/setup/import'
      preLoaderRoute: typeof SetupImportRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/create': {
      id: '/setup/create'
      path: '/create'
      fullPath: '/setup/create'
      preLoaderRoute: typeof SetupCreateRouteImport
      parentRoute: typeof SetupRoute
    }
    '/library/tags': {
      id: '/library/tags'
      path: '/tags'
      fullPath: '/library/tags'
      preLoaderRoute: typeof LibraryTagsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/history': {
      id: '/library/history'
      path: '/history'
      fullPath: '/library/history'
      preLoaderRoute: typeof LibraryHistoryRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/favorites': {
      id: '/library/favorites'
      path: '/favorites'
      fullPath: '/library/favorites'
      preLoaderRoute: typeof LibraryFavoritesRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/lab/transactions': {
      id: '/lab/transactions'
      path: '/transactions'
      fullPath: '/lab/transactions'
      preLoaderRoute: typeof LabTransactionsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/layer-2': {
      id: '/lab/layer-2'
      path: '/layer-2'
      fullPath: '/lab/layer-2'
      preLoaderRoute: typeof LabLayer2RouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/control': {
      id: '/lab/control'
      path: '/control'
      fullPath: '/lab/control'
      preLoaderRoute: typeof LabControlRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/blocks': {
      id: '/lab/blocks'
      path: '/blocks'
      fullPath: '/lab/blocks'
      preLoaderRoute: typeof LabBlocksRouteImport
      parentRoute: typeof LabRoute
    }
    '/library/articles/$slug': {
      id: '/library/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/library/articles/$slug'
      preLoaderRoute: typeof LibraryArticlesSlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/lab/tx/$txid': {
      id: '/lab/tx/$txid'
      path: '/tx/$txid'
      fullPath: '/lab/tx/$txid'
      preLoaderRoute: typeof LabTxTxidRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LabRouteChildren {
  LabBlocksRoute: typeof LabBlocksRoute
  LabControlRoute: typeof LabControlRoute
  LabLayer2Route: typeof LabLayer2Route
  LabTransactionsRoute: typeof LabTransactionsRoute
  LabIndexRoute: typeof LabIndexRoute
  LabTxTxidRoute: typeof LabTxTxidRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabBlocksRoute: LabBlocksRoute,
  LabControlRoute: LabControlRoute,
  LabLayer2Route: LabLayer2Route,
  LabTransactionsRoute: LabTransactionsRoute,
  LabIndexRoute: LabIndexRoute,
  LabTxTxidRoute: LabTxTxidRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface LibraryRouteChildren {
  LibraryFavoritesRoute: typeof LibraryFavoritesRoute
  LibraryHistoryRoute: typeof LibraryHistoryRoute
  LibraryTagsRoute: typeof LibraryTagsRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryArticlesSlugRoute: typeof LibraryArticlesSlugRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryFavoritesRoute: LibraryFavoritesRoute,
  LibraryHistoryRoute: LibraryHistoryRoute,
  LibraryTagsRoute: LibraryTagsRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryArticlesSlugRoute: LibraryArticlesSlugRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface SetupRouteChildren {
  SetupCreateRoute: typeof SetupCreateRoute
  SetupImportRoute: typeof SetupImportRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCreateRoute: SetupCreateRoute,
  SetupImportRoute: SetupImportRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface WalletRouteChildren {
  WalletManagementRoute: typeof WalletManagementRoute
  WalletReceiveRoute: typeof WalletReceiveRoute
  WalletSendRoute: typeof WalletSendRoute
  WalletWalletsRoute: typeof WalletWalletsRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletManagementRoute: WalletManagementRoute,
  WalletReceiveRoute: WalletReceiveRoute,
  WalletSendRoute: WalletSendRoute,
  WalletWalletsRoute: WalletWalletsRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  WalletRoute: WalletRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
