/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as PersonalRegtestRouteImport } from './routes/personal-regtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as PersonalRegtestIndexRouteImport } from './routes/personal-regtest/index'
import { Route as SetupImportRouteImport } from './routes/setup/import'
import { Route as SetupCreateRouteImport } from './routes/setup/create'
import { Route as PersonalRegtestTxTxidRouteImport } from './routes/personal-regtest/tx.$txid'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRegtestRoute = PersonalRegtestRouteImport.update({
  id: '/personal-regtest',
  path: '/personal-regtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const PersonalRegtestIndexRoute = PersonalRegtestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonalRegtestRoute,
} as any)
const SetupImportRoute = SetupImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCreateRoute = SetupCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SetupRoute,
} as any)
const PersonalRegtestTxTxidRoute = PersonalRegtestTxTxidRouteImport.update({
  id: '/tx/$txid',
  path: '/tx/$txid',
  getParentRoute: () => PersonalRegtestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personal-regtest': typeof PersonalRegtestRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/wallets': typeof WalletsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/personal-regtest/': typeof PersonalRegtestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/personal-regtest/tx/$txid': typeof PersonalRegtestTxTxidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/wallets': typeof WalletsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/personal-regtest': typeof PersonalRegtestIndexRoute
  '/setup': typeof SetupIndexRoute
  '/personal-regtest/tx/$txid': typeof PersonalRegtestTxTxidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/personal-regtest': typeof PersonalRegtestRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/wallets': typeof WalletsRoute
  '/setup/create': typeof SetupCreateRoute
  '/setup/import': typeof SetupImportRoute
  '/personal-regtest/': typeof PersonalRegtestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/personal-regtest/tx/$txid': typeof PersonalRegtestTxTxidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/personal-regtest'
    | '/receive'
    | '/send'
    | '/settings'
    | '/setup'
    | '/wallets'
    | '/setup/create'
    | '/setup/import'
    | '/personal-regtest/'
    | '/setup/'
    | '/personal-regtest/tx/$txid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/receive'
    | '/send'
    | '/settings'
    | '/wallets'
    | '/setup/create'
    | '/setup/import'
    | '/personal-regtest'
    | '/setup'
    | '/personal-regtest/tx/$txid'
  id:
    | '__root__'
    | '/'
    | '/personal-regtest'
    | '/receive'
    | '/send'
    | '/settings'
    | '/setup'
    | '/wallets'
    | '/setup/create'
    | '/setup/import'
    | '/personal-regtest/'
    | '/setup/'
    | '/personal-regtest/tx/$txid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonalRegtestRoute: typeof PersonalRegtestRouteWithChildren
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-regtest': {
      id: '/personal-regtest'
      path: '/personal-regtest'
      fullPath: '/personal-regtest'
      preLoaderRoute: typeof PersonalRegtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/personal-regtest/': {
      id: '/personal-regtest/'
      path: '/'
      fullPath: '/personal-regtest/'
      preLoaderRoute: typeof PersonalRegtestIndexRouteImport
      parentRoute: typeof PersonalRegtestRoute
    }
    '/setup/import': {
      id: '/setup/import'
      path: '/import'
      fullPath: '/setup/import'
      preLoaderRoute: typeof SetupImportRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/create': {
      id: '/setup/create'
      path: '/create'
      fullPath: '/setup/create'
      preLoaderRoute: typeof SetupCreateRouteImport
      parentRoute: typeof SetupRoute
    }
    '/personal-regtest/tx/$txid': {
      id: '/personal-regtest/tx/$txid'
      path: '/tx/$txid'
      fullPath: '/personal-regtest/tx/$txid'
      preLoaderRoute: typeof PersonalRegtestTxTxidRouteImport
      parentRoute: typeof PersonalRegtestRoute
    }
  }
}

interface PersonalRegtestRouteChildren {
  PersonalRegtestIndexRoute: typeof PersonalRegtestIndexRoute
  PersonalRegtestTxTxidRoute: typeof PersonalRegtestTxTxidRoute
}

const PersonalRegtestRouteChildren: PersonalRegtestRouteChildren = {
  PersonalRegtestIndexRoute: PersonalRegtestIndexRoute,
  PersonalRegtestTxTxidRoute: PersonalRegtestTxTxidRoute,
}

const PersonalRegtestRouteWithChildren = PersonalRegtestRoute._addFileChildren(
  PersonalRegtestRouteChildren,
)

interface SetupRouteChildren {
  SetupCreateRoute: typeof SetupCreateRoute
  SetupImportRoute: typeof SetupImportRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCreateRoute: SetupCreateRoute,
  SetupImportRoute: SetupImportRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonalRegtestRoute: PersonalRegtestRouteWithChildren,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
